ISSUE 46: Implement HTTPD environment variable.

diff --git a/etc/apache-bootstrap b/etc/apache-bootstrap
--- a/etc/apache-bootstrap
+++ b/etc/apache-bootstrap
@@ -19,7 +19,7 @@ OPTS_SERVICE_USER_GROUP_PASSWORD="${SERVICE_USER_GROUP_PASSWORD:-$(get_password 
 OPTS_SERVICE_USER_PASSWORD="${SERVICE_USER_PASSWORD:-$(get_password 8)}"
 OPTS_SUEXECUSERGROUP="${SUEXECUSERGROUP:-false}"
 
-if [[ ! -d ${OPTS_APP_HOME_DIR} ]] && [[ -d ${OPTS_APP_HOME_DIR_TEMPLATE} ]]; then
+if [[ ! -d ${OPTS_APP_HOME_DIR} ]] && [[ -d ${APP_HOME_DIR_TEMPLATE} ]]; then
 	echo "Recreate the ${OPTS_APP_HOME_DIR} directory."
 	mkdir -p ${OPTS_APP_HOME_DIR}
 fi
@@ -39,8 +39,27 @@ if [[ ${OPTS_APP_HOME_DIR} != /var/www/app ]]; then
 	unlink /home/app && ln -s ${OPTS_APP_HOME_DIR} /home/app
 fi
 
+# Server MPM
+HTTPD_MPM_PREFORK=/usr/sbin/httpd
+HTTPD_MPM_WORKER=/usr/sbin/httpd.worker
+HTTPD=${HTTPD:-${HTTPD_MPM_PREFORK}}
+if [[ ${HTTPD} == ${HTTPD_MPM_PREFORK} ]]; then
+	echo "Apache Server MPM: Prefork"
+	sed -i \
+	-e "s~HTTPD=${HTTPD_MPM_WORKER}~#HTTPD=${HTTPD_MPM_WORKER}~g" \
+	/etc/sysconfig/httpd
+elif [[ ${HTTPD} == ${HTTPD_MPM_WORKER} ]]; then
+	echo "Apache Server MPM: Worker"
+	sed -i \
+	-e "s~#HTTPD=${HTTPD_MPM_WORKER}~HTTPD=${HTTPD_MPM_WORKER}~g" \
+	/etc/sysconfig/httpd
+else
+	echo "ERROR: Apache Server MPM (${HTTPD}) unknown."
+	exit 1
+fi
+
 # If users need to change the vhost.conf the SSL version can be rebuilt if it is deleted
-if [[ ${OPTS_APACHE_MOD_SSL_ENABLED} == "true" ]] && [[ ! -f ${OPTS_APP_HOME_DIR}/vhost-ssl.conf ]] && [[ -f ${OPTS_APP_HOME_DIR}/vhost.conf ]]; then
+if [[ ${OPTS_APACHE_MOD_SSL_ENABLED} == true ]] && [[ ! -f ${OPTS_APP_HOME_DIR}/vhost-ssl.conf ]] && [[ -f ${OPTS_APP_HOME_DIR}/vhost.conf ]]; then
 	echo "Rebuilding the SSL VirtualHost configuration."
 	cp -pf ${OPTS_APP_HOME_DIR}/vhost.conf ${OPTS_APP_HOME_DIR}/vhost-ssl.conf
 
